In [40]:
import numpy as np
import pandas as pd
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [66]:
%run random_tour.py

In [67]:
random_tour.shape

(102, 3)

In [102]:
def CreateTenthStepArray(tour):
    "Creates array with zeros where 10th step - first step can be removed"
    tenth_step = np.zeros(len(tour)) # initilise the length of tour
    cnt = -1
    for x in np.nditer(tenth_step, op_flags=['readwrite']):
        cnt += 1
        if cnt%10 == 0:
            x[...] = 1

    return(tenth_step)

In [128]:
def CalcCostSimple(tour):
    """simple function to calc cost function
    input
    tour, np array, 3 cols: X,Y,prime
    """
    Xdiff = np.diff(tour[:,0])
    Ydiff = np.diff(tour[:,1])
    
    euclid = (Xdiff**2 + Ydiff**2)
    
    #### L should be carrot penalty
    primes_and_tenths = CreateTenthStepArray(tour)[1:] * tour[:,2][1:] # get array with zeros where 10th step and prime city = 1, otherwise 0
    print('Number of cities identified as having prime on 10th journey: ', primes_and_tenths.sum())
    L = (primes_and_tenths*0.1) + 1 # make array with elements either 1 or 1.1 
    
    cost = (euclid*L).sum()
    
    return cost

In [129]:
CalcCostSimple(random_tour)

Number of cities identified as having prime on 10th journey:  0.0


678712610.62522686

In [117]:
CalcCostSimple(random_tour)

678712610.62522686

In [118]:
678712610.62522686

678712610.6252269

In [112]:
len(random_tour)

102

In [115]:
random_tour[:,2].shape

(102,)

In [109]:
CreateTenthStepArray(random_tour)[1:] * cities[:,2]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [111]:
CreateTenthStepArray(random_tour)[1:].shape

(101,)

In [110]:
cities.shape

(101, 3)

In [101]:
len(random_tour)

102

In [100]:
random_tour.shape[0]

102

In [93]:

    
X

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
CalcCostSimple(random_tour)

678712610.62522686

In [70]:
%%timeit
CalcCostSimple(random_tour)

15.6 µs ± 372 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [65]:
CalcCostSimple(random_tour)

592097566.12679625

In [45]:
np.diff(random_tour[:,0]).shape

(101,)

In [61]:
X = np.ones((random_tour[:,1].shape))
X*1.1

array([ 1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,  1.1,
        1.1,  1.1,  1.1])

In [59]:
cnt = 0
for i in X:
    cnt += 1

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [50]:
cities[:,2]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.])

In [43]:
break

SyntaxError: 'break' outside loop (<ipython-input-43-6aaf1f276005>, line 1)

In [8]:
from utils import GetCityArray, GetStartCityFromArray, RemoveCityFromArray

In [11]:
cities= GetCityArray('./data/clean_s100.csv')

start_city = GetStartCityFromArray(cities)

cities = RemoveCityFromArray(cities)

In [21]:
np.random.shuffle(cities)

(100, 3)

In [32]:
start_city.shape

(3,)

In [35]:
start_city

array([  316.83673906,  2202.34070734,     0.        ])

In [38]:
start_city = start_city.reshape(1,-1)

In [39]:
np.concatenate((start_city,cities,start_city),axis=0)

array([[  3.16836739e+02,   2.20234071e+03,   0.00000000e+00],
       [  3.69731291e+03,   2.72293091e+03,   0.00000000e+00],
       [  2.66009599e+03,   2.02636793e+03,   0.00000000e+00],
       [  2.83955708e+03,   3.24092635e+03,   0.00000000e+00],
       [  4.57616180e+03,   2.08404995e+03,   1.00000000e+00],
       [  4.79579604e+03,   1.84328572e+03,   0.00000000e+00],
       [  4.85728263e+03,   2.88245512e+03,   0.00000000e+00],
       [  2.49009930e+03,   2.12262943e+03,   1.00000000e+00],
       [  2.41401843e+03,   3.07049446e+02,   0.00000000e+00],
       [  2.03560635e+03,   1.03226741e+03,   0.00000000e+00],
       [  3.34772923e+03,   2.96124261e+03,   0.00000000e+00],
       [  3.44798899e+03,   3.14559625e+02,   0.00000000e+00],
       [  3.64921174e+02,   2.25413440e+03,   0.00000000e+00],
       [  1.51461954e+02,   2.42594178e+03,   0.00000000e+00],
       [  1.38225470e+03,   2.91966994e+03,   0.00000000e+00],
       [  4.40235307e+03,   1.04473714e+03,   0.0000000

In [31]:
start_city.reshape(1,-1).shape

(1, 3)

In [25]:
cities.shape

(100, 3)

In [22]:
arr = np.arange(9).reshape((3, 3))
print(arr)
np.random.shuffle(arr)
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [3]:
df =pd.read_csv('./data/clean_s100.csv')
df.head()

CityId            X            Y  prime
0       0   316.836739  2202.340707      0
1   15079  2889.264992   793.259095      0
2  166894  3577.379159  3045.207474      0
3  188954  2182.005310  3255.008018      0
4  142701   160.791040  2413.769294      0

In [11]:
cities = df[['X','Y']].values
primes = df['prime'].values

In [13]:
primes.shape

(101,)

In [14]:
cities.shape

(101, 2)

In [28]:
from utils import GetCityArray

In [29]:
cities,primes = GetCityArray('./data/clean_s100.csv')

In [30]:
cities.shape

(101, 2)

In [33]:
start = cities[0,:]
start

array([  316.83673906,  2202.34070734])

In [45]:
cities_popped_top = np.delete(cities,[0],axis=0)

In [50]:
np.delete(primes,[0],axis=0).shape

(100,)